version: '2'
services:
  image-service:
    build: ./image-service/docker
    restart: always
    ports: 
      - "8080:8080"
  web:
    build: ./web
    restart: always
    ports: 
      - "8888:3000"